openapi: 3.0.0
info:
  title: Faculty Management API
  version: 1.0.0
paths:
  /lecturers:
    get:
      summary: Get a list of all lecturers
      responses:
        200:
          description: List of lecturers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
    post:
      summary: Add a new lecturer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
  /lecturers/{staffNumber}:
    get:
      summary: Get details of a specific lecturer by staff number
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lecturer details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
    put:
      summary: Update an existing lecturer's information
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lecturer'
      responses:
        200:
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lecturer'
    delete:
      summary: Delete a lecturer's record by staff number
      parameters:
        - name: staffNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: No content
  /courses/{courseCode}/lecturers:
    get:
      summary: Get all lecturers that teach a certain course
      parameters:
        - name: courseCode
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of lecturers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
  /offices/{officeNumber}/lecturers:
    get:
      summary: Get all lecturers that sit in the same office
      parameters:
        - name: officeNumber
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: List of lecturers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lecturer'
components:
  schemas:
    Lecturer:
      type: object
      properties:
        staffNumber:
          type: string
        officeNumber:
          type: string
        staffName:
          type: string
        title:
          type: string
        courses:
          type: array
          items:
            type: string
    Course:
      type: object
      properties:
        courseName:
          type: string
        courseCode:
          type: string
        nqfLevel:
          type: integer
